name: solana_phantom_wallet_app
description: Flutter app for Phantom wallet integration with Solana

publish_to: 'none'

version: 1.3.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # UI components
  cupertino_icons: ^1.0.2
  
  # URL launcher for deep links
  url_launcher: ^6.2.4
  
  # HTTP requests for Solana RPC
  http: ^1.2.0
  
  # Crypto utilities
  crypto: ^3.0.3
  
  # JSON handling
  convert: ^3.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/